// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOAi-YFX07PzFRkmn-4Kw7395zzeeEh7k',
    appId: '1:58003684894:web:82d53e429285766dfeb80f',
    messagingSenderId: '58003684894',
    projectId: 'cmsc23-rgludovico',
    authDomain: 'cmsc23-rgludovico.firebaseapp.com',
    storageBucket: 'cmsc23-rgludovico.appspot.com',
    measurementId: 'G-38VCE61L43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTnbQmrY3v4jFJcmQXMJmUqLC-VCKq2b0',
    appId: '1:58003684894:android:6d96888401eac381feb80f',
    messagingSenderId: '58003684894',
    projectId: 'cmsc23-rgludovico',
    storageBucket: 'cmsc23-rgludovico.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAODh0Wt7Y3Nl5NGfdSJ-Mfbf7Gab4mVZs',
    appId: '1:58003684894:ios:70f5e554eebbf65dfeb80f',
    messagingSenderId: '58003684894',
    projectId: 'cmsc23-rgludovico',
    storageBucket: 'cmsc23-rgludovico.appspot.com',
    iosClientId: '58003684894-6p4708dbov7kocd8o6f4mdi62fddh4ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAODh0Wt7Y3Nl5NGfdSJ-Mfbf7Gab4mVZs',
    appId: '1:58003684894:ios:70f5e554eebbf65dfeb80f',
    messagingSenderId: '58003684894',
    projectId: 'cmsc23-rgludovico',
    storageBucket: 'cmsc23-rgludovico.appspot.com',
    iosClientId: '58003684894-6p4708dbov7kocd8o6f4mdi62fddh4ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
